supportedlang: # https://docs.aws.amazon.com/comprehend/latest/dg/how-languages.html
  zh: CHS
  zh-TW: CHT
  de: DE
  en: EN
  es: ES
  fr: FR
  id: ID
  it: IT
  ja: JP
  ko: KR
  pt: PT
  ru: RU
  th: TH
  tr: TR
  vi: VI
  
supportedmodel: #bedrock anthropic model you want to use
  - anthropic.claude-3-haiku-20240307-v1:0
  - anthropic.claude-3-sonnet-20240229-v1:0
  - anthropic.claude-3-5-sonnet-20240620-v1:0
  - anthropic.claude-3-opus-20240229-v1:0

support: # support contact info
  - XXXXX

upload_bucket:
  name: 750521193989-24-07-24-00-59-42-dynamodb-rag-bucket