supportedlang: # https://docs.aws.amazon.com/comprehend/latest/dg/how-languages.html
  简体中文: zh-cn
  繁体中文: zh-tw
  德语: de-de
  英语: en-us
  西班牙语: es-es
  法语: fr-fr
  印尼语: id-id
  意大利语: it-it
  日语: ja-jp
  韩语: ko-kr
  葡萄牙语: pt-pt
  俄语: ru-ru
  泰语: th-th
  土耳其语: tr-tr
  越南语: vi-vn

supportedmodel: #bedrock anthropic model you want to use
  - anthropic.claude-3-haiku-20240307-v1:0
  - anthropic.claude-3-sonnet-20240229-v1:0
  - anthropic.claude-3-5-sonnet-20240620-v1:0
  - anthropic.claude-3-opus-20240229-v1:0

support: # support contact info
  - xyz

upload_bucket:
  name: bucket_placeholder

deploy_region: # region you want to deploy
  - region_placeholder
